{
 "title": "Parsing",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"products\"\nFROM products\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"nutrients\"\nFROM nutrients\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"portions\"\nFROM portions\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Успешные запросы",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(number) AS \"Порций\"\nFROM success_grafana\nWHERE `type` = 1\nORDER BY created_at"
    },
    {
     "rawSql": "SELECT\n  SUM(number) AS \"Контент страниц\"\nFROM success_grafana\nWHERE `type` = 2\nORDER BY created_at"
    },
    {
     "rawSql": "SELECT\n  SUM(number) AS \"Всего\"\nFROM success_grafana\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Ошибки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"Forms_content\"\nFROM errors\nWHERE\n  $__timeFilter(created_at) AND\n  message LIKE 'Can`t found title'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"invalid_portion\"\nFROM errors\nWHERE\n  $__timeFilter(created_at) AND\n  message LIKE 'invalid portion'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"timeout_content\"\nFROM errors\nWHERE\n  $__timeFilter(created_at) AND\n  message LIKE '%Timeout was reached: Operation timed out after % milliseconds%'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"429\"\nFROM errors\nWHERE\n  $__timeFilter(created_at) AND\n  message LIKE '%429%'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"proxy\"\nFROM errors\nWHERE\n  $__timeFilter(created_at) AND\n  message LIKE '%PROXY%'\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  }
 ]
}